<a href="https://colab.research.google.com/github/reddy-nithin/CS5530-PDS-InClassAssignements/blob/main/PDS_ICP_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Required Packages

In [ ]:
import pandas as pd

# Importing Data

In [ ]:
data_url="https://raw.githubusercontent.com/JuliaData/CSV.jl/refs/heads/main/test/testfiles/Sacramentorealestatetransactions.csv"
df = pd.read_csv(data_url)
df.head(10)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
0,3526 HIGH ST,SACRAMENTO,95838,CA,2,1,836,Residential,Wed May 21 00:00:00 EDT 2008,59222,38.631913,-121.434879
1,51 OMAHA CT,SACRAMENTO,95823,CA,3,1,1167,Residential,Wed May 21 00:00:00 EDT 2008,68212,38.478902,-121.431028
2,2796 BRANCH ST,SACRAMENTO,95815,CA,2,1,796,Residential,Wed May 21 00:00:00 EDT 2008,68880,38.618305,-121.443839
3,2805 JANETTE WAY,SACRAMENTO,95815,CA,2,1,852,Residential,Wed May 21 00:00:00 EDT 2008,69307,38.616835,-121.439146
4,6001 MCMAHON DR,SACRAMENTO,95824,CA,2,1,797,Residential,Wed May 21 00:00:00 EDT 2008,81900,38.519470,-121.435768
5,5828 PEPPERMILL CT,SACRAMENTO,95841,CA,3,1,1122,Condo,Wed May 21 00:00:00 EDT 2008,89921,38.662595,-121.327813
6,6048 OGDEN NASH WAY,SACRAMENTO,95842,CA,3,2,1104,Residential,Wed May 21 00:00:00 EDT 2008,90895,38.681659,-121.351705
7,2561 19TH AVE,SACRAMENTO,95820,CA,3,1,1177,Residential,Wed May 21 00:00:00 EDT 2008,91002,38.535092,-121.481367
8,11150 TRINITY RIVER DR Unit 114,RANCHO CORDOVA,95670,CA,2,2,941,Condo,Wed May 21 00:00:00 EDT 2008,94905,38.621188,-121.270555
9,7325 10TH ST,RIO LINDA,95673,CA,3,2,1146,Residential,Wed May 21 00:00:00 EDT 2008,98937,38.700909,-121.442979

# Coding exercise

In [35]:
#Find the number of the columns in the data frame
df.shape[1]

12

In [ ]:
# Find the mean of the house prices
df.price.mean()

234144.26395939087

In [ ]:
# Find the median of the house prices
df.price.median()

213750.0

In [33]:
# Find the different types of property in the dataset
df.type.unique()

array(['Residential', 'Condo', 'Multi-Family', 'Unkown'], dtype=object)

In [32]:
# Find the maximum price of a "condo" in the dataset
df[df.type == 'Condo'].sort_values('price', ascending=False,).head(1)

,street,city,zip,state,beds,baths,sq__ft,type,sale_date,price,latitude,longitude
511,1322 SUTTER WALK,SACRAMENTO,95816,CA,0,0,0,Condo,Mon May 19 00:00:00 EDT 2008,360000,38.53805,-121.5047

In [37]:
# Find the maximum price of a "condo" in the dataset
df[df.type == 'Condo']['price'].max()

360000

In [29]:
# Find the mean of each type of property in the dataset
df.groupby('type').mean(numeric_only=True)

,zip,beds,baths,sq__ft,price,latitude,longitude
type,,,,,,,
Condo,95756.648148,1.666667,1.240741,760.425926,150082.185185,38.638827,-121.365441
Multi-Family,95780.384615,4.461538,3.076923,2046.923077,224534.692308,38.597955,-121.352973
Residential,95750.001091,2.966194,1.791712,1338.625954,239186.162486,38.606001,-121.355978
Unkown,95682.000000,0.000000,0.000000,0.000000,275000.000000,38.643470,-120.888183

In [34]:
df.type.value_counts()

type
Residential     917
Condo            54
Multi-Family     13
Unkown            1
Name: count, dtype: int64